<?php
declare(strict_types=1);

defined('TYPO3') || die();

use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;

(static function (): void {
    // Extension key used in EXT: paths.
    $extensionKey = 'anatolkin_mosaic_gallery';

    // Internal plugin signature used by Extbase and TypoScript.
    // It must match the signature generated by configurePlugin('MosaicGallery', 'Pi1').
    // => mosaicgallery_pi1
    $pluginSignature = 'mosaicgallery_pi1';

    // Ensure that the list_type items configuration is an array.
    if (
        !isset($GLOBALS['TCA']['tt_content']['columns']['list_type']['config']['items'])
        || !is_array($GLOBALS['TCA']['tt_content']['columns']['list_type']['config']['items'])
    ) {
        $GLOBALS['TCA']['tt_content']['columns']['list_type']['config']['items'] = [];
    }

    // Register the plugin in the "Insert plugin" list.
    $GLOBALS['TCA']['tt_content']['columns']['list_type']['config']['items'][] = [
        'LLL:EXT:anatolkin_mosaic_gallery/Resources/Private/Language/locallang_be.xlf:plugin.title',
        $pluginSignature,
        'mosaic-gallery-plugin',
    ];

    // Enable the FlexForm for this plugin.
    $GLOBALS['TCA']['tt_content']['types']['list']['subtypes_addlist'][$pluginSignature]
        = 'pi_flexform';

    // Attach the plugin FlexForm.
    ExtensionManagementUtility::addPiFlexFormValue(
        $pluginSignature,
        'FILE:EXT:' . $extensionKey . '/Configuration/FlexForms/MosaicGallery.xml'
    );
})();
