services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Anatolkin\MosaicGallery\Controller\GalleryController: ~

  Anatolkin\MosaicGallery\Service\FolderImageProvider: ~

  Anatolkin\MosaicGallery\Service\GalleryMetadataOverrideResolver: ~

  Anatolkin\MosaicGallery\Service\GalleryImageSorter: ~

  Anatolkin\MosaicGallery\Backend\Form\Element\MetadataOverridesElement: ~

  Anatolkin\MosaicGallery\Upgrades\MosaicGalleryCTypeMigration: ~
